# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RadarMessage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'RadarMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RadarMessage.proto\"\xdb\x01\n\x0cRadarMessage\x12#\n\x06spokes\x18\x02 \x03(\x0b\x32\x13.RadarMessage.Spoke\x1a\xa5\x01\n\x05Spoke\x12\r\n\x05\x61ngle\x18\x01 \x01(\r\x12\x14\n\x07\x62\x65\x61ring\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\r\n\x05range\x18\x03 \x01(\r\x12\x11\n\x04time\x18\x04 \x01(\x04H\x01\x88\x01\x01\x12\x10\n\x03lat\x18\x06 \x01(\x01H\x02\x88\x01\x01\x12\x10\n\x03lon\x18\x07 \x01(\x01H\x03\x88\x01\x01\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x42\n\n\x08_bearingB\x07\n\x05_timeB\x06\n\x04_latB\x06\n\x04_lonB\nZ\x08../radarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RadarMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010../radar'
  _globals['_RADARMESSAGE']._serialized_start=23
  _globals['_RADARMESSAGE']._serialized_end=242
  _globals['_RADARMESSAGE_SPOKE']._serialized_start=77
  _globals['_RADARMESSAGE_SPOKE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
